services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "60000:8080"
#  node:
#    image: node:20.16
#    restart: always
#    working_dir: /app
#    volumes:
#      - ./:/app
#    ports:
#      - "3000:3000"
#    command: "npm start"
