version: "2.22"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Dream1702!
  adminer:
    image: adminer
    restart: always
    ports:
      - "60000:8080" 
  node:
    image: node:20.16
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm start"
